# Generated by Django 5.2.4 on 2025-07-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
        migrations.AddField(
            model_name='content',
            name='guide_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('guide_card', 'Guide Card'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.section'),
        ),
    ]
