from django.urls import path
from .views import (
    ListCoursesView,
    CourseDetailsView,
    AddToCartView,
    ViewCartView,
    RemoveFromCartView,
    ApplyDiscountCodeView,
    CheckoutView,
    CreateCourseView,
    UpdateCourseView,
    DeleteCourseView,
    UserPurchasedCoursesView,
    CreateSectionView,
    UpdateSectionView,
    DeleteSectionView,
    CreateContentView,
    UpdateContentBySectionView,
    DeleteContentBySectionView,
    ListAllCoursesAdminView,
    CourseOutlineView,
    SimulatePaymentView,
    MyCoursesView,
    PurchaseHistoryView,
    HomePageCoursesView,
    TopSellingCoursesView,
    CourseSectionsStatusView,
    SubmitVideoProgressView,
    CheckNextSectionAccessView,
    GetCurrentSectionContent,
    SubmitChallengeView,
)

urlpatterns = [
    path("courses", ListCoursesView.as_view(), name="list_courses"),
    path("courses/<int:course_id>", CourseDetailsView.as_view(), name="course_details"),
    path("cart", AddToCartView.as_view(), name="add_to_cart"),
    path("view-cart", ViewCartView.as_view(), name="view_cart"),
    path(
        "remove-from-cart/<int:course_id>",
        RemoveFromCartView.as_view(),
        name="remove_from_cart",
    ),
    path("apply-discount", ApplyDiscountCodeView.as_view(), name="apply_discount"),
    path("checkout", CheckoutView.as_view(), name="checkout"),
    path("admin/courses", CreateCourseView.as_view(), name="create_course"),
    path(
        "admin/courses/<int:course_id>/update/",
        UpdateCourseView.as_view(),
        name="update_course",
    ),
    path(
        "admin/courses/<int:course_id>/delete/",
        DeleteCourseView.as_view(),
        name="delete_course",
    ),
    path(
        "admin/users/<int:user_id>/courses",
        UserPurchasedCoursesView.as_view(),
        name="user_purchased_courses",
    ),
    path(
        "admin/courses/<int:course_id>/sections",
        CreateSectionView.as_view(),
        name="create_section",
    ),
    path(
        "admin/courses/<int:course_id>/sections/<int:section_id>/update",
        UpdateSectionView.as_view(),
        name="update_section",
    ),
    path(
        "admin/courses/<int:course_id>/sections/<int:section_id>/delete",
        DeleteSectionView.as_view(),
        name="delete_section",
    ),
    path(
        "admin/courses/<int:course_id>/sections/<int:section_id>/content",
        CreateContentView.as_view(),
        name="create_content",
    ),
    path(
        "admin/courses/<int:course_id>/sections/<int:section_id>/content/update",
        UpdateContentBySectionView.as_view(),
        name="update_content_by_section",
    ),
    path(
        "admin/courses/<int:course_id>/sections/<int:section_id>/content/delete",
        DeleteContentBySectionView.as_view(),
        name="delete_content_by_section",
    ),
    path(
        "admin/list-courses",
        ListAllCoursesAdminView.as_view(),
        name="list_all_courses_admin",
    ),
    path(
        "courses/<int:course_id>/outline",
        CourseOutlineView.as_view(),
        name="course_outline",
    ),
    path("simulate-payment", SimulatePaymentView.as_view(), name="simulate_payment"),
    path("my-courses", MyCoursesView.as_view(), name="my_courses"),
    path("purchase-history", PurchaseHistoryView.as_view(), name="purchase_history"),
    path("home/courses", HomePageCoursesView.as_view(), name="home_courses"),
    path(
        "home/courses/top-selling",
        TopSellingCoursesView.as_view(),
        name="top_selling_courses",
    ),
    path(
        "courses/<int:course_id>/sections/status",
        CourseSectionsStatusView.as_view(),
        name="course_sections_status",
    ),
    path(
        "content/<int:content_id>/watch-progress",
        SubmitVideoProgressView.as_view(),
        name="submit_video_progress",
    ),
    path(
        "sections/check-next-access",
        CheckNextSectionAccessView.as_view(),
        name="check_next_section_access",
    ),
    path(
        "courses/<int:course_id>/section/<int:current_section_order>/content",
        GetCurrentSectionContent.as_view(),
        name="get_current_section_content",
    ),
    path(
        "challenges/<int:challenge_id>/submit",
        SubmitChallengeView.as_view(),
        name="submit_challenge",
    ),
]
